apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-proxy
  namespace: golang-app
  labels:
    app: golang-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-proxy
  template:
    metadata:
      labels:
        app: golang-proxy
    spec:
      containers:
      - name: golang-proxy
        image: prvtrgstr.azurecr.io/nginx-golang-mysql/proxy-golang:408
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 60
      terminationGracePeriodSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1